// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOL5ZudlKul5kO0wT7nxInw3k4nGvhAbs',
    appId: '1:774333710981:web:92eba2a426304e4dbe9fec',
    messagingSenderId: '774333710981',
    projectId: 'gear-studio-info-tracker-ea46e',
    authDomain: 'gear-studio-info-tracker-ea46e.firebaseapp.com',
    databaseURL:
        'https://gear-studio-info-tracker-ea46e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gear-studio-info-tracker-ea46e.appspot.com',
    measurementId: 'G-SYKHBCBY8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtDWP_ym5cPCYSskoDnJzR1RfgsUxrWk',
    appId: '1:774333710981:android:3bbeebdd60fae26cbe9fec',
    messagingSenderId: '774333710981',
    projectId: 'gear-studio-info-tracker-ea46e',
    databaseURL:
        'https://gear-studio-info-tracker-ea46e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gear-studio-info-tracker-ea46e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRZ5U2LKBStu-nyn7xBA_o86nCdXmZC8',
    appId: '1:774333710981:ios:6801bbc24810ef51be9fec',
    messagingSenderId: '774333710981',
    projectId: 'gear-studio-info-tracker-ea46e',
    databaseURL:
        'https://gear-studio-info-tracker-ea46e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gear-studio-info-tracker-ea46e.appspot.com',
    iosBundleId: 'com.example.gearStudioInfoTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRZ5U2LKBStu-nyn7xBA_o86nCdXmZC8',
    appId: '1:774333710981:ios:052cb1b1b7a531a8be9fec',
    messagingSenderId: '774333710981',
    projectId: 'gear-studio-info-tracker-ea46e',
    databaseURL:
        'https://gear-studio-info-tracker-ea46e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gear-studio-info-tracker-ea46e.appspot.com',
    iosBundleId: 'com.example.gearStudioInfoTracker.RunnerTests',
  );
}
